### ISSUE TITLE
Setup test suit to accept PR

### ISSUE THREAD

**Issue by prateekbh** [kysonic/riot-mui#14]
PR can be really volatile...
lets setup test cases for the tags

**Comment by kysonic** [comment]
@prateekbh Do you have any experience regarding testing of riot.js tags? What is the best practice in this case? Mocha?

**Comment by prateekbh** [comment]
yeah so basically i use mocha-phantomjs and do functional tests...
function existance and function input output simple tests

**Comment by kysonic** [comment]
Got it. It could be helpful. I'll try to create something like that ;-)
