### ISSUE TITLE
Version confliction between GitHub(0.0.14) and npm(0.0.15)

### ISSUE THREAD

**Issue by satoko-a** [kysonic/riot-mui#22]
Hi,

I tried this package with `npm install --save-dev riot-mui` but it didn't work.
I found riot-mui version is 0.0.15 at my project but it is 0.0.14 at this GitHub repository.

```
  // package.json at my project
  "riot-mui": "0.0.15",
```

And [at npm(riot-mui)](https://www.npmjs.com/package/riot-mui), the version is 0.0.15 too.
Maybe something is wrong with your npm package, I thought.

With installation from GitHub(as shown below), I can use this library without errors.
Very cool! Thanks :D

```
  "riot-mui": "git@github.com:kysonic/riot-mui.git#4e34676273f186dd6887bc20d1f92c8531e256d7",
```

**Comment by kysonic** [comment]
@satoko-a Maybe, i'll check npm package.  

UPD: I checked version and updated npm package. Thanks for your notification!

**Comment by satoko-a** [comment]
@kysonic 
Thanks. It works well :+1:
