### ISSUE TITLE
toggle component?

### ISSUE THREAD

**Issue by falxcerebri** [kysonic/riot-mui#30]
Do you think implementing toggle component would be useful?
I will try to make a Pull Request with such feature.

**Comment by kysonic** [comment]
@falxcerebri Yes. Why not? If i understood correctly you meant this 

https://material.google.com/components/expansion-panels.html 

If so it would be great.

**Comment by falxcerebri** [comment]
I was thinking about this:
http://www.material-ui.com/#/components/toggle
but I see that this toggle is actually out of scope for pure material design.

**Comment by kysonic** [comment]
@falxcerebri I think it's not a big deal. I'm not sure we should follow those rules stricktly. Please apply your pull request i'm sure it would be better to collect another component in riot-mui especially if somobody will use it in its projects.
