### ISSUE TITLE
issues with valid on material-input

### ISSUE THREAD

**Issue by mikey0000** [kysonic/riot-mui#35]
I can neither add a function or use regex without errors. This is with riot 2.6.7

when using regex I get the following error
```
SyntaxError: Unexpected token )
```

I get function undefined errors with the function.

**Comment by kysonic** [comment]
@mikey0000 

I think it can be related with attributes parsing. I will check it out. Thanks.

**Comment by kysonic** [comment]
@mikey0000 

I was trying to reproduce described bug but it didn't happen... Could you please provide your regular expression? Or your material input HTML. I have tested regex validation [Here](https://github.com/kysonic/riot-mui/blob/master/index.html#L143). You can take this example and build your own meterial-input using it.

**Comment by mikey0000** [comment]
@kysonic dunno what i was doing but entering regex into valid is working fine. sorry for the false alarm, if I figure out what I was doing before to do it I'll pop it in here.

**Comment by kysonic** [comment]
@mikey0000 

No worries)
