### ISSUE TITLE
Provide source code for gh-page

### ISSUE THREAD

**Issue by IxDay** [kysonic/riot-mui#4]
Hello,

I checked out your project and though that it would be cool if the sources for the gh-page were available. So that people could test in practice the library you are providing

**Comment by kysonic** [comment]
Hello @IxDay, yes it's a greate idea. I'll add source code of gh-page. Actually i wanted to add more tutorials and examples for those purposes but unfortunately i don't have much time for this.

**Comment by kysonic** [comment]
@IxDay i decided to create new repo for gh-page: 

https://github.com/kysonic/riot-mui-page
