### ISSUE TITLE
Webpack

### ISSUE THREAD

**Issue by Joxit** [kysonic/riot-mui#46]
Should we add webpack in this project ?

**Comment by kysonic** [comment]
@Joxit , why not. I love webpack. If i will find some time to do it, I will ))

**Comment by Joxit** [comment]
Ok, Don't worry, I'm on it :smile:

**Comment by kysonic** [comment]
@Joxit , you are the best! ))

**Comment by Joxit** [comment]
ha ha, it's my first time with webpack, I would certainly need your help :sweat_smile:
