### ISSUE TITLE
Can't mount button example ( and more)

### ISSUE THREAD

**Issue by Ollink** [kysonic/riot-mui#6]
Setup : 

``` html
<html>  
    <head>
        <link href="bower_components/riot-mui/build/styles/riot-mui.min.css" rel="stylesheet">

        <script src="bower_components/riot/riot+compiler.js"></script>

        <script src="bower_components/riot-mui/build/js/riot-mui-mixins-min.js"></script>
        <script src="bower_components/riot-mui/build/js/riot-mui.js"></script> 

        <script src="https://cdn.jsdelivr.net/riotgear/2.1.3/rg.min.js"></script>
    </head>
    <body>
        <material-button>
            <div class="text">Button</div>
        </material-button>
        <script>
                   riot.mount('*');
        </script>
    </body>
</html>
```

Error : 
![mui1](https://cloud.githubusercontent.com/assets/9133476/11870645/e15126f6-a4c9-11e5-95e2-a622403f1883.PNG)
![mui2](https://cloud.githubusercontent.com/assets/9133476/11870648/eefbb7c6-a4c9-11e5-9fe7-7857b71db155.PNG)

When using

``` .html
<material-input placeholder="Just input"></material-input>  
```

I get

![mui3](https://cloud.githubusercontent.com/assets/9133476/11870668/0ea135f6-a4ca-11e5-9deb-3576b43fe128.PNG)

With other components i get other random errors, so it seems like i'm doing something wrong in general. Am i missing any dependencies, or do i have to mount it differently ?

**Comment by Ollink** [comment]
A global replace substituting '{{' for '{' and '}}' for '}' did fix it.
Do i have to set an option somewhere to use '{{' ? Because i am using single '{'.

**Comment by kysonic** [comment]
Yes, @Vantraninthena , you are right. You have to set up 

```
riot.settings.brackets = '{{ }}'; 
```

before this line:

```
riot.mount('*');
```

In riot MUI i used double curly braces. I know that it's unusual for riot but i decided to do this because i like this style. If it will be necessary, i will release version of riot MUI with "single curly braces".

**Comment by Ollink** [comment]
Thanks for the answer.
However, i'm using single brackets in my project and if i change the bracket setting my own tags are not working anymore.

Can i use both versions of brackets together ? If not, an MUI with single curly braces would definitely be necessary in my opinion.

**Comment by kysonic** [comment]
I've created a new issue for riotjs regarding problem with brackets. 

[https://github.com/riot/riot/issues/1470](https://github.com/riot/riot/issues/1470)

And few words about first problem: Dependencies of components will be important only when you will be using some build system, because in this case you will require components directly, but when you require whole script, all of components will be loaded at a time. Anyway i will check your example.

**Comment by kysonic** [comment]
@Vantraninthena, Yeah. How we were thinking example with double curly brackets works fine.  

http://joxi.ru/gmv66wqhxqOb6m 
http://joxi.ru/EA4nnOkFDo7yPm 

If there is no way to resolve conflict with curly brackets, i will adapt this library to usual syntax.

**Comment by Ollink** [comment]
Let's wait for the response on the issue you opened.

In the meantime you could add that information ( and later the possible solution) about the double brackets to your README.md.
Will close this issue, thanks for your help .

**Comment by kysonic** [comment]
@Vantraninthena i changed syntax. Because i think that majority will use "{" instead "{{".

**Comment by Ollink** [comment]
Good to know.
But shouldn't a recompile result into a riot.tag2 where it doesn't matter whether you use '{' or '{{'  because it gets its brackets as last argument ?

``` javascript
riot.tag2 = function(name, html, css, attrs, fn, bpair)
```

**Comment by kysonic** [comment]
@Vantraninthena , how @aMarCruz said 

_This feature needs more testing before being implemented._

Anyway in this case we need to create a new gulp plugin supporting those features.
