### ISSUE TITLE
input and textarea error

### ISSUE THREAD

**Issue by Ollink** [kysonic/riot-mui#7]
Basically the same error i mentioned in my first post in #6 about the input, sadly i didn't check the input example again, my bad.

The compiled code ( and your src) for input and textera contain referenes to 

``` javascript
this['{opts.name}']
this['{this.name}']
```

The html contains

``` html
<input type="{opts.type || \'text\'}" disabled="{disabled}" placeholder="{opts.placeholder}" onkeyup="{changeValue}" value="{value}" autocomplete="off" name="{this.name}"> 
```

but the i guess the reference with brackets causes an eror for the compiler somehow ?

Fixed this issue by simply giving a static name ( e.g. 'input'), but you probably intended something different here.

**Comment by kysonic** [comment]
@Vantraninthena  Sorry for delay. Yes, you are right. There was a problem with custom names of input and textarea. It was necessary to transmit name from material-input (material-textarea) to sub input (textarea) into those tags. Before version 2.3 it worked fine. Then riot's developers made some changes regarding options. Currently all of options transmited to tag will be changed, for instance if we transmit "waves-color" in tag's attribute, into opts it will be represented like opts.wavesColor. Also construction like "this['{this.name}']" stopped to work as well. Proceeding from it i've made fixes regarding these issues. And added [extended version](https://github.com/kysonic/riot-mui/blob/master/examples/vanilla/index.html) of vanilla example.

**Comment by Ollink** [comment]
Thanks for the fix, haven't had the time to test it yet, will close the issue as soon as possible.
