### ISSUE TITLE
delayed click

### ISSUE THREAD

**Issue by prateekbh** [kysonic/riot-mui#9]
sometimes i need to show the waves traveling to the user and when this transition ends... i'd like to fire some event then like "onwaveend" on the root element...

it looks better by design that way...

e.g. material-button should fire onwaveend when waves animation has ended

**Comment by kysonic** [comment]
Yeah. It sounds quite logical. I'll implement this feature as soon as possible.

**Comment by kysonic** [comment]
@prateekbh Check [this](https://github.com/kysonic/riot-mui/blob/master/examples/vanilla/index.html#L146-L152) out.

**Comment by prateekbh** [comment]
does it work like <material-button onwaveend="{someRiotFunction}" ???

**Comment by kysonic** [comment]
@prateekbh Unfortunately nope. Those events was made using [observable](http://riotjs.com/api/observable/) functionality of riot tag. How far i know there is no way to link function from attributes (opts) with custom events. In this case you have to get instance of riot tag and setup listener 

buttonTag.on('wavestart',function(wave){});
buttonTag.on('waveend',function(){});

**Comment by prateekbh** [comment]
wait i'll fix this.. :) 
PR on its way

**Comment by kysonic** [comment]
@prateekbh Okay, i'm waiting.

**Comment by kysonic** [comment]
@prateekbh Could i close this issue?

**Comment by prateekbh** [comment]
yeah go ahead.. :)
